# Generated by Django 4.0.1 on 2023-07-06 14:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=30, verbose_name='Status Name')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(help_text='Введите фамилию', max_length=30, verbose_name='Last Name')),
                ('firstname', models.CharField(help_text='Введите имя', max_length=30, verbose_name='First Name')),
                ('sername', models.CharField(help_text='Введите отчество', max_length=30, verbose_name='Sername')),
                ('birth_date', models.DateField(default=datetime.date.today, help_text='Введите дату рождения', verbose_name='Birth date')),
                ('skills', models.CharField(help_text='Заполните резюме', max_length=500, verbose_name='Skills')),
                ('email', models.EmailField(help_text='Введите электронную почту', max_length=254, verbose_name='Email')),
                ('contact_info', models.CharField(help_text='Введите номер телефона', max_length=15, verbose_name='Contact Information')),
                ('links', models.CharField(blank=True, help_text='Ссылки на социальные сети, для связи', max_length=300, null=True, verbose_name='Links')),
                ('extrainfo', models.CharField(blank=True, help_text='Дополнительная информация', max_length=300, null=True, verbose_name='Extra Information')),
                ('direction', models.CharField(help_text='Введите направление обучения', max_length=100, verbose_name='Direction')),
                ('graduate_date', models.DateField(default=datetime.date.today, help_text='Введите дату поступления', verbose_name='Graduate Date')),
                ('company_title', models.CharField(help_text='Введите название компании', max_length=100, verbose_name='Company Title')),
                ('company_info', models.CharField(blank=True, help_text='Информация о компании', max_length=300, null=True, verbose_name='Company Information')),
                ('company_links', models.CharField(help_text='Укажите сайт компании', max_length=500, verbose_name='Company Information')),
                ('job_title', models.CharField(help_text='Укажите свою должность', max_length=100, verbose_name='Job Title')),
                ('department', models.CharField(help_text='Укажите свою кафедру', max_length=30, verbose_name='Department')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProfile.status')),
            ],
        ),
    ]
