# Generated by Django 4.2.1 on 2023-07-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_links',
            field=models.CharField(help_text='Укажите сайт компании', max_length=500, verbose_name='Company Link'),
        ),
    ]
