# Generated by Django 4.2.1 on 2023-07-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0002_alter_profile_company_links'),
        ('MyProfile', '0002_profile_photo'),
    ]

    operations = [
    ]
