# Generated by Django 4.0.1 on 2023-07-07 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0019_alter_newsarticle_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 7, 56, 57, 438174, tzinfo=utc), verbose_name='date published'),
        ),
    ]
